### ISSUE TITLE
Cannot see Respeaker 2-mic hat on Pi Zero 2 W

### ISSUE THREAD

**Issue by formatBCE** [rhasspy/wyoming-satellite#110]
I recently installed satellite to Pi Zero 2 W with Respeaker 2-mic hat. Then i screwed up my install, so started from scratch.

Apparently, manual changed a bit (different dependency files at least). And although driver installation succeeds, i can't see the hat in `aplay -L` or `arecord -L`

I tried from scratch 2 times, and now even tried to install dependencies from respeaker.txt, but pip cannot install `spidev` (error in header file).

Question is: did someone actually try to install satellite from scratch on new readme?

UPD: tried same hat on Pi 4B, and it worked. Not on Pi Zero 2W though.

**Comment by llluis** [comment]
The only needed step to make the speaker work is the drivers listed here: https://github.com/rhasspy/wyoming-satellite/blob/master/docs/tutorial_2mic.md#install-software

```
cd wyoming-satellite/
sudo bash etc/install-respeaker-drivers.sh
sudo reboot
```

The `requirements_respeaker.txt` was introduced with the installer and was never mentionned in the tutorial... 
Anyway, those two libs are required only to make the leds work, not the speaker.

The only thing changed in the tutorial was the txt filenames, but the contents are the same.

**Comment by formatBCE** [comment]
> The only needed step to make the speaker work is the drivers listed here: https://github.com/rhasspy/wyoming-satellite/blob/master/docs/tutorial_2mic.md#install-software
> 
> ```
> cd wyoming-satellite/
> sudo bash etc/install-respeaker-drivers.sh
> sudo reboot
> ```
> 
> The `requirements_respeaker.txt` was introduced with the installer and was never mentionned in the tutorial... 
> Anyway, those two libs are required only to make the leds work, not the speaker.
> 
> The only thing changed in the tutorial was the txt filenames, but the contents are the same. 

Exactly. And I did install drivers first. Moreover, I did it 3 times today. Pi zero, Pi 4B, and Pi zero again. 

Although files didn't change, there could be new core for Raspberry OS for Pi Zero, or some other dependency changed...

**Comment by llluis** [comment]
OS image dates from december.

![image](https://github.com/rhasspy/wyoming-satellite/assets/708868/5cf80765-a4f4-4ff8-92ba-1ef83b1e234c)

I flashed a new SD, ran:
```
sudo apt-get update
sudo apt-get install --no-install-recommends  \
  git \
  python3-venv
git clone https://github.com/rhasspy/wyoming-satellite.git
cd wyoming-satellite/
sudo bash etc/install-respeaker-drivers.sh
sudo reboot
```

and everything works... 

```
$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: vc4hdmi [vc4-hdmi], device 0: MAI PCM i2s-hifi-0 [MAI PCM i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: seeed2micvoicec [seeed-2mic-voicecard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 [bcm2835-i2s-wm8960-hifi wm8960-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```


```
$ aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
sysdefault
    Default Audio Device
lavrate
    Rate Converter Plugin Using Libav/FFmpeg Library
samplerate
    Rate Converter Plugin Using Samplerate Library
speexrate
    Rate Converter Plugin Using Speex Resampler
jack
    JACK Audio Connection Kit
oss
    Open Sound System
pulse
    PulseAudio Sound Server
upmix
    Plugin for channel upmix (4,6,8)
vdownmix
    Plugin for channel downmix (stereo) with a simple spacialization
default
playback
capture
dmixed
array
hw:CARD=vc4hdmi,DEV=0
    vc4-hdmi, MAI PCM i2s-hifi-0
    Direct hardware device without any conversions
plughw:CARD=vc4hdmi,DEV=0
    vc4-hdmi, MAI PCM i2s-hifi-0
    Hardware device with all software conversions
sysdefault:CARD=vc4hdmi
    vc4-hdmi, MAI PCM i2s-hifi-0
    Default Audio Device
hdmi:CARD=vc4hdmi,DEV=0
    vc4-hdmi, MAI PCM i2s-hifi-0
    HDMI Audio Output
dmix:CARD=vc4hdmi,DEV=0
    vc4-hdmi, MAI PCM i2s-hifi-0
    Direct sample mixing device
usbstream:CARD=vc4hdmi
    vc4-hdmi
    USB Stream Output
hw:CARD=seeed2micvoicec,DEV=0
    seeed-2mic-voicecard, bcm2835-i2s-wm8960-hifi wm8960-hifi-0
    Direct hardware device without any conversions
plughw:CARD=seeed2micvoicec,DEV=0
    seeed-2mic-voicecard, bcm2835-i2s-wm8960-hifi wm8960-hifi-0
    Hardware device with all software conversions
sysdefault:CARD=seeed2micvoicec
    seeed-2mic-voicecard, bcm2835-i2s-wm8960-hifi wm8960-hifi-0
    Default Audio Device
dmix:CARD=seeed2micvoicec,DEV=0
    seeed-2mic-voicecard, bcm2835-i2s-wm8960-hifi wm8960-hifi-0
    Direct sample mixing device
usbstream:CARD=seeed2micvoicec
    seeed-2mic-voicecard
    USB Stream Output
$
```

That's a Pi Zero 2 W too.

**Comment by formatBCE** [comment]
@llluis yup, doing it the same way.

Apparently, it's faulty headers on my Pi Zero... Since it works on 4B with same hat.

Appreciate your help checking this. Closing issue.

**Comment by formatBCE** [comment]
> > Apparently, it's faulty headers on my Pi Zero... Since it works on 4B with same hat.
> 
> Oh noes... Try to melt the solder on the pins, it could be just a cold joint... specially if you bought the pi with pins already. 
> Good luck.

Thanks, plan to do it first deal tomorrow

**Comment by formatBCE** [comment]
> > Apparently, it's faulty headers on my Pi Zero... Since it works on 4B with same hat.
> 
> Oh noes... Try to melt the solder on the pins, it could be just a cold joint... specially if you bought the pi with pins already. Good luck.

Just FYI: yes, it was soldering. Interesting, that it worked for a month before, and broke somewhere in between old and new firmware. Probably, i broke it when pulling out from case. :)
Anyways - thanks for your help!
