### ISSUE TITLE
Wakeword seems detected but nothing happens

### ISSUE THREAD

**Issue by olskar** [rhasspy/wyoming-satellite#113]
I see the following in the logs, when I say the wakeword the leds light up but this is the last thing I see in wyoming-satellite.service. 

Ideas?

Feb 14 13:27:10 satelite systemd[1]: Started wyoming-satellite.service - Wyoming Satellite.
Feb 14 13:27:11 satelite run[1072]: INFO:root:Ready
Feb 14 13:27:11 satelite run[1072]: INFO:root:Connected to services
Feb 14 13:27:11 satelite run[1074]: Recording raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
Feb 14 13:27:13 satelite run[1072]: INFO:root:Connected to server
Feb 14 13:27:13 satelite run[1072]: INFO:root:Waiting for wake word

**Comment by llluis** [comment]
Impossible to guess just with this info.

Please run all the services with the `--debug` flag.

**Comment by olskar** [comment]
> Impossible to guess just with this info.
> 
> Please run all the services with the `--debug` flag.

Thanks,

Not much wiser from the debug, do you see anything weird?

journalctl -u wyoming-satellite.service -f
Feb 14 15:50:31 satelite run[1091]: DEBUG:root:Detected IP: 192.168.1.100
Feb 14 15:50:31 satelite run[1091]: DEBUG:root:Zeroconf discovery enabled (name=b827eb53bea1, host=None)
Feb 14 15:50:31 satelite run[1091]: DEBUG:root:Connecting to mic service: ['arecord', '-D', 'plughw:CARD=seeed2micvoicec,DEV=0', '-r', '16000', '-c', '1', '-f', 'S16_LE', '-t', 'raw']
Feb 14 15:50:31 satelite run[1091]: DEBUG:root:Connecting to snd service: ['aplay', '-D', 'plughw:CARD=seeed2micvoicec,DEV=0', '-r', '22050', '-c', '1', '-f', 'S16_LE', '-t', 'raw']
Feb 14 15:50:31 satelite run[1091]: DEBUG:root:Connecting to wake service: tcp://127.0.0.1:10400
Feb 14 15:50:31 satelite run[1091]: DEBUG:root:Connecting to event service: tcp://127.0.0.1:10500
Feb 14 15:50:31 satelite run[1091]: INFO:root:Connected to services
Feb 14 15:50:31 satelite run[1093]: Recording raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
Feb 14 15:50:31 satelite run[1091]: DEBUG:root:Connected to mic service
Feb 14 15:50:31 satelite run[1091]: DEBUG:root:Connected to wake service
Feb 14 15:50:35 satelite run[1091]: DEBUG:root:Server set: 469409527952
Feb 14 15:50:35 satelite run[1091]: INFO:root:Connected to server
Feb 14 15:50:35 satelite run[1091]: INFO:root:Waiting for wake word
Feb 14 15:50:35 satelite run[1091]: DEBUG:root:Connected to event service
Feb 14 15:50:37 satelite run[1091]: DEBUG:root:Ping enabled
Feb 14 15:50:45 satelite run[1091]: DEBUG:root:Streaming audio

**Comment by llluis** [comment]
> Feb 14 15:50:45 satelite run[1091]: DEBUG:root:Streaming audio

This is only logged after wake word detection and the satellite streaming to Home Assistant.
The next log would be the transcription of what you said.

`Feb 14 09:54:03 nabu1 run[1588]: DEBUG    Event(type='transcript', data={'text': 'Test'}, payload=None)`

If nothing happens after, I would say to look at Home Assistant logs.
Also, do you see the sensor "Assist in progress" change when saying the wake word?
Do you have the pipeline configured and tested with the assist?

**Comment by olskar** [comment]
Thanks, there were indeed errors in HA :)
