### ISSUE TITLE
[Feature request] : skip_seconds

### ISSUE THREAD

**Issue by lightsabata** [rhasspy/wyoming-satellite#12]
Hi @synesthesiam !
I know it is kind of a "niche" feature, but would it be possible to add a kind of `--skip_seconds` option so the sentence registered is ignoring the first miliseconds of the audio.

To explain : Before in rhasspy  i set into my home a kind of a virtual butler (Alfred, from Batman thanks to porcupine custom wake word). 

In this scenario, a wake sound is enabled and plays an audio file wich is in fact a tts who says "monsieur ?" ("sir ?" but in french). Obvously this kind of setting mess the intent recognition in many ways.

Even with a noise cancelling parameter, a specific microphone with build-in eco cancelation and with skip_word added in on Home Assistant, the wake word sound is by many times registered as part of the the intent and/or mess the vad process.

On rhasspy 2.5 i use to have the `skip_seconds` parameter enabled on my config file.

i saw on the code that you've added a  buffer_seconds option, is the oposite option hard to implement ?
i was trying to add a `asyncio sleep`  command before vad start but if im'not wrong it cannot work since it ues timestamp data, but i'm not sure and i'am not a python expert

By the way a huge thanks for all of your work ! you cannot imagine how it is now central to my house and my family

cheer's

**Comment by joie96** [comment]
I haven't tried it much, but maby you can get around this by not using --awake-wav and instead using  the --detection-command (like the readme suggets).

For example: --detection-command 'aplay -r 22050 -c 1 -f S16_LE -t raw ./sounds/awake.wav'

**Comment by lightsabata** [comment]
Hi !
Thanks for your respond ! unfortunately  i respectfully don't understand how this method can solve my problem.
is the recording timestanp is starting after the  --detection-command has finished ? after some test it doesn't seems to be the case

**Comment by joie96** [comment]
Hey, you are absolutly right. After some testing I've noticed that using a custom detection-command  doest not work. So we need a "skip_second" option.

**Comment by lightsabata** [comment]
Yes, unfortunately it's been 3 weeks that i trying to add this function without. My trough is that is juste the exact opposite of "vad-buffer-seconds" function, but it seems that's it is much much more complicated than that.

**Comment by synesthesiam** [comment]
Hey @lightsabata, sorry to get back to you so late! I'll take a look at implementing this :slightly_smiling_face: 
I need to implement debug recording first, so I can make sure it's working!

**Comment by lightsabata** [comment]
hi @synesthesiam, happy new year! 
Thanks for your respond, we've seen that you've been very busy with the latest HA updates.
Exited to know that you're thinking about the implementation!

**Comment by lightsabata** [comment]
The commit 73604f9a71edc167986d15f95121db9484fb11d4 implemented the feature.
Many thanks to @synesthesiam for all his work !

**Comment by synesthesiam** [comment]
You're welcome! This is currently implemented for just the awake WAV. Do you think it's worth it to add for the end of voice command WAV too?

**Comment by lightsabata** [comment]
I'm flattered you asked for my opinion about that. Right now i don’t see any possible applications that can require this feature
