### ISSUE TITLE
wyoming-satellite update

### ISSUE THREAD

**Issue by ddppddpp** [rhasspy/wyoming-satellite#120]
What would be the correct way to check for a new version of this code and update the existing satellites?

**Comment by freakshock88** [comment]
It seems I was able to update with these commands:

Stop service
```bash
sudo systemctl disable --now wyoming-satellite.service
```

Pull latest changes 
```bash
cd /wyoming-satellite
git pull
```

Run install script 
```
script/setup
```

Reenable service
```bash
sudo systemctl enable --now wyoming-satellite.service
```

**Comment by daveLeiser** [comment]
> It seems I was able to update with these commands:
> 
> Stop service
> 
> ```shell
> sudo systemctl disable --now wyoming-satellite.service
> ```
> 
> Pull latest changes
> 
> ```shell
> cd /wyoming-satellite
> git pull
> ```
> 
> Run install script
> 
> ```
> script/setup
> ```
> 
> Reenable service
> 
> ```shell
> sudo systemctl enable --now wyoming-satellite.service
> ```

This will keep all the configs setup during the initial installation, right? And i guess it's the same for openWakeword and the LED controller? 
Would be great to have a Doc guiding through the update process like the installation process.

**Comment by donburch888** [comment]
Noting that there have been changes since I installed my wyoming-satellite, I tried this proceedure.  (Last time I removed the directory and started from scratch). 

1. I had installed wyoming-satellite in my pi user, so the cd command didn't need the "/"

2. script/setup gave an error - but it looks like an intended linked file - and did not finish
```
pi@HA-voice-2:~/wyoming-satellite $ script/setup
Traceback (most recent call last):
  File "/home/pi/wyoming-satellite/script/setup", line 18, in <module>
    builder.create(_VENV_DIR)
  File "/usr/lib/python3.9/venv/__init__.py", line 73, in create
    self.setup_python(context)
  File "/usr/lib/python3.9/venv/__init__.py", line 243, in setup_python
    copier(context.executable, path)
  File "/usr/lib/python3.9/venv/__init__.py", line 186, in symlink_or_copy
    shutil.copyfile(src, dst)
  File "/usr/lib/python3.9/shutil.py", line 244, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/usr/bin/python3' and '/home/pi/wyoming-satellite/.venv/bin/python3' are the same file
pi@HA-voice-2:~/wyoming-satellite $ 
```

**Comment by ddppddpp** [comment]
stopping the service (sudo systemctl stop wyoming_satellite.service), cloning issuing git pull and then starting the service seems to work as expected.
