### ISSUE TITLE
error: these packages do not match the hashes from the requirements file

### ISSUE THREAD

**Issue by mitrokun** [rhasspy/wyoming-satellite#139]
An error occurred during installation. I checked it twice. I strictly followed the steps outlined in the instructions. How to solve the problem?

```
  Downloading https://www.piwheels.org/simple/sympy/sympy-1.12-py3-none-any.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━ 3.4/5.7 MB 86.7 kB/s eta 0:00:27
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have upd           ated the package versions, please update the hashes. Otherwise, examine the package conte           nts carefully; someone may have tampered with them.
    sympy from https://www.piwheels.org/simple/sympy/sympy-1.12-py3-none-any.whl#sha256=1           620ac1eff186c7359cd48d30b0ad366b854f283d2fe38f9b5fd1a9fcc247fc0 (from onnxruntime<2,>=1.1           0.0->pysilero-vad==1.0.0->-r requirements_vad.txt (line 1)):
        Expected sha256 1620ac1eff186c7359cd48d30b0ad366b854f283d2fe38f9b5fd1a9fcc247fc0
             Got        924bf27ac0024bb14f41bd89e09024be6815ac98d3d7eb2d1e70993303553cb9

```
During the second attempt, the last part was different
```
             Got        a72147fe3179ea6314a375da61029f7ab7f26949e6065b14c1dd23b09711f350

```

**Comment by jmtatsch** [comment]
If you have a bad internet connection that can happen if there were transfer issues. 
Just try again and add the "--no-cache-dir" to the pip install command.

**Comment by mitrokun** [comment]
> add the "--no-cache-dir"
Where should I add this key? Is that right?

python3 -m venv .venv
.venv/bin/pip3 install --no-cache-dir
.venv/bin/pip3 install --upgrade pip
.venv/bin/pip3 install --upgrade wheel setuptools
.venv/bin/pip3 install \
  -f 'https://synesthesiam.github.io/prebuilt-apps/' \
  -r requirements.txt \
  -r requirements_audio_enhancement.txt \
  -r requirements_vad.txt

**Comment by mitrokun** [comment]
I have attempted this ten times, including using this specific parameter. Each time, an error occurred during the download of "https://www.piwheels.org/simple/sympy/sympy-1.12-py3-none-any.whl "

**Comment by jmtatsch** [comment]
Maybe package is broken on pypi side? Or someone is manipulating your connection to inject some malicious code.

**Comment by mitrokun** [comment]
> to inject some malicious code.

I highly doubt it. 
I tried a lot of other things, but removing 2Mic HAT helped🤣
I can't even imagine why he's affecting this.

**Comment by nmalone17** [comment]
I am having a similar issue. I get this everytime I run pip3 install stuff:

ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    sympy from https://www.piwheels.org/simple/sympy/sympy-1.13.3-py3-none-any.whl#sha256=e925802e5d4708a0cceae3cae0ffb568385a7c6f9d8eeab652b0e71630cbc275 (from onnxruntime<2,>=1.10.0->pysilero-vad==1.0.0->wyoming_satellite==1.4.1):
        Expected sha256 e925802e5d4708a0cceae3cae0ffb568385a7c6f9d8eeab652b0e71630cbc275
             Got        01898eed9cbda0eaf9ac7bd23c2fd15ac0fcac0b5d0899f1b3ddfe0c72a90b36

**Comment by LeoLTM** [comment]
Got the same issue... Simply re-running the command again fixed it.
