### ISSUE TITLE
Add device to home assistant without  zeroconf

### ISSUE THREAD

**Issue by KristijanL** [rhasspy/wyoming-satellite#142]
Hi,

i have a smart speaker Xiaomi LX06 with limited space so i cant run zeroconf and other service is already using zeroconf ports, so how can i manual add the device to the home assistant? 
i have temporary run with zeroconf using /tmp FS to get the satellite automatically configured in home assistant and then restart it without zeroconf and its still working, but i don't know if it will continue to work in the future.

Maybe there is some documentation on this, but I am just incompetent to find it? 

Kristijan

**Comment by chatziko** [comment]
You don't need zeroconf, just go to Settings / Devices & services / Add integration / Wyoming protocol and enter the satellites IP and port.

**Comment by KristijanL** [comment]
i am an idiot 🤦 
because of the "protocol" in "Wyoming protocol" integration, i thought this was something else
thank you for the clarification!
