### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tflite-runtime-nightly (from versions: none)

### ISSUE THREAD

**Issue by sayam93** [rhasspy/wyoming-satellite#156]
The openwakeword script probably needs an update because when I run the following command:

git clone https://github.com/rhasspy/wyoming-openwakeword.git
cd wyoming-openwakeword
script/setup

I get this error towards the end:

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement tflite-runtime-nightly (from versions: none)
ERROR: No matching distribution found for tflite-runtime-nightly
Traceback (most recent call last):
File "/home/pi/wyoming-openwakeword/script/setup", line 26, in
subprocess.check_call(pip + ["install", "-r", str(_PROGRAM_DIR / "requirements.txt")])
File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/pi/wyoming-openwakeword/.venv/bin/python3', '-m', 'pip', 'install', '-r', '/home/pi/wyoming-openwakeword/requirements.txt']' returned non-zero exit status 1.

Please help!

**Comment by kdutton1964** [comment]
In openwakeword requirements.txt I changed...
tflite-runtime-nightly
wyoming==1.5.3

to

tflite-runtime
wyoming==1.5.3
deleting -nightly

This worked for me, I also performed a successful install few days ago. Went back to do fresh install and it failed.

**Comment by sayam93** [comment]
Thanks! worked like a charm. Using remote wake word was a nightmare!
