### ISSUE TITLE
TTS response very fast and high pitched

### ISSUE THREAD

**Issue by daveLeiser** [rhasspy/wyoming-satellite#184]
**Problem description:**
TTS responses are high pitched and quite fast spoken.

**Setup:**
I am using a RPI 0 2 W with a respeaker 2 mic PI hat and a small speaker connected via JST.
I followed the tutorial here on GitHub for the installation

This is in my config:

```
[Service]
Type=simple
ExecStart=/home/hidden/wyoming-satellite/script/run \
 --name 'kitchen satellite' \
 --uri 'tcp://0.0.0.0:10700' \
 --mic-command 'arecord -D plughw:CARD=seeed2micvoicec,DEV=0 -r 16000 -c 1 -f S16_LE -t raw' \
 --snd-command 'aplay -D plughw:CARD=seeed2micvoicec,DEV=0 -r 22050 -c 1 -f S16_LE -t raw' \
 --snd-command-rate 16000 \
 --mic-auto-gain 5 \
 --mic-noise-suppression 2 \
 --wake-uri 'tcp://127.0.0.1:10400' \
 --wake-word-name 'hey_jarvis' \
 --event-uri 'tcp://127.0.0.1:10500'
WorkingDirectory=/home/hidden/wyoming-satellite
Restart=always
RestartSec=1

```
On other devices using the same Assist pipeline as for this satellite in Home Assistant I do not have the same problem, so I guess this is an issue with my config here.

Does someone have an idea what’s wrong here?

**Comment by synesthesiam** [comment]
Try changing `--snd-command-rate` to 22050.

**Comment by daveLeiser** [comment]
Solved, thanks for the fast reply.
