### ISSUE TITLE
Timer example?

### ISSUE THREAD

**Issue by critchie** [rhasspy/wyoming-satellite#187]
I’m trying to get timers to work. Will there be an update to the README.md on how to do this?

I’ve updating my satellite with the latest code and rebooted. When I say “Start timer for 5 seconds” my satellite tells me the timer started but then I get no indication the tier finished.

**Comment by synesthesiam** [comment]
You can specify a WAV file to be played as shown here: https://github.com/rhasspy/wyoming-satellite/?tab=readme-ov-file#sounds

For more advanced use cases, see the `--timer-*` event commands: https://github.com/rhasspy/wyoming-satellite/?tab=readme-ov-file#event-commands
I use these event commands in my example timer web server: https://github.com/rhasspy/wyoming-satellite/blob/master/examples/websocket-service/timers.html

**Comment by critchie** [comment]
Thank you. I glanced right over that and missed it. All is working now.
