### ISSUE TITLE
How to configure wyoming-satellite to have voice detection on raspberry pi as well as Home Assistant

### ISSUE THREAD

**Issue by owingst** [rhasspy/wyoming-satellite#203]
I read some where that it is possible to get the voice detection to work on wyoming-satellite RPi and not just Home Assistant.  In other words, how to get my wyoming-satellite to detect voice command and stream audio on RPi. When I setup a satellite, wake word does not work until I configure the satellite in Home Assistant. Make sense?

**Comment by thespawnat** [comment]
https://github.com/rhasspy/wyoming-satellite?tab=readme-ov-file#local-wake-word-detection should help

**Comment by owingst** [comment]
Thanks You!

**Comment by tannisroot** [comment]
> Thanks You!

if you've resolved your issue, please close, thank you!
