### ISSUE TITLE
No awake or done sounds

### ISSUE THREAD

**Issue by SvenSvenson38** [rhasspy/wyoming-satellite#218]
I've tried multiple configurations of the --awake-wav in my satellite config, but i've not had any sound at any point. I'd like to make a custom sound, but have been trying to just get anything working first. Audio is fine as I get my voice assistant through the speaker without any issue, and the LED service works, it's just the audio feedback isn't coming through. Below is my configuration file. Thanks in advance
*edited to reflect current syntax*
__________________________

[Unit]
Description=Wyoming Satellite
Wants=network-online.target
After=network-online.target
Requires=wyoming-openwakeword.service
Requires=2mic_leds.service

[Service]
Type=simple
ExecStart=/home/voicesatellite/wyoming-satellite/script/run \\
    --name 'my satellite' \\
    --uri 'tcp://0.0.0.0:10700' \\
    --event-uri 'tcp://127.0.0.1:10500' \\
    --mic-auto-gain 5 \\
    --mic-noise-suppression 2 \\
    --mic-command 'arecord -D plughw:CARD=seeed2micvoicec,DEV=0 -r 16000 -c 1 -f S16_LE -t raw' \\
    --snd-command 'aplay -D plughw:CARD=seeed2micvoicec,DEV=0 -r 22050 -c 1 -f S16_LE -t raw'
    --wake-uri 'tcp://127.0.0.1:10400' \\
    --wake-word-name 'hey_woodhouse' \\
    --awake-wav sounds/awake.wav \\
    --done-wav sounds/done.wav \\
    --vad
WorkingDirectory=/home/voicesatellite/wyoming-satellite
Restart=always
RestartSec=1

[Install]
WantedBy=default.target

**Comment by dreed47** [comment]
try adding the full path to the sound files

```
          --awake-wav '/opt/wyoming-satellite/sounds/awake.wav' \
          --done-wav '/opt/wyoming-satellite/sounds/done.wav' \
          --timer-finished-wav '/opt/wyoming-satellite/sounds/timer_finished.wav'
```

**Comment by SvenSvenson38** [comment]
Thanks, but no luck with that either! No adjustment to that, with or without quotes, or the shortened path. The LED timers also change too fast, so without sound it's unclear if it's still listening!

**Comment by CBDesignS** [comment]
if you have split the command line then it looks like you are missing \ on each of the split lines

have a read of https://github.com/rhasspy/wyoming-satellite/issues/189

**Comment by SvenSvenson38** [comment]
Hey,
for some reason they didn't past in, but they are there and i have edited to show properly! Interestingly though, i can't put one after the --snd-command line or i lose wake word recognition.. I wonder if this also explains my issue trying to get on device wake word recognition working. Would that cause anything after that line to be ignored, and therefore it's streaming everything through to HA and not locally?

**Comment by SvenSvenson38** [comment]
Issue resolved! Basically, removing all splits fixed both issues! I'm unsure why (there were no random spaces etc) but without any splits i can reorder everything as well and have no issues with dropping any service. Strange...
