### ISSUE TITLE
Still being developed?

### ISSUE THREAD

**Issue by LiveForToday** [rhasspy/wyoming-satellite#251]
Just wondering if this is still alive? Haven't seen any updates in some time.

**Comment by synesthesiam** [comment]
Yes, I've just been very busy with the release of Nabu Casa's voice hardware.

**Comment by LiveForToday** [comment]
> Yes, I've just been very busy with the release of Nabu Casa's voice hardware.

Thank you, appreciate all your hard work. Happy holidays.
