### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by XanderStrike** [rhasspy/wyoming-satellite#252]
Last release was February, no commits in 6 months, issues piling up, open PRs are ignored.

Images from the docker compose file have been [removed from dockerhub](https://hub.docker.com/u/rhasspy) ☹️ 

If this project is abandoned please update the readme to reflect that before people spend time trying to use it.

**Comment by Fraddles** [comment]
Still an ongoing thing...

https://github.com/rhasspy/wyoming-satellite/issues/251
