### ISSUE TITLE
WARNING:root:Mic service disconnected.

### ISSUE THREAD

**Issue by TDX44** [rhasspy/wyoming-satellite#53]
I'll first say I'm a little off the tutorial at this point and still testing. I'm using a RP4 with a RP 64bit os. I'm waiting on a USB mic but currently I'm testing with a bluetooth bose headset. From my understanding this shouldn't be an issue because I can both record and play back the recording through the headset with "default" selected as my mic and speaker. 

```shell
arecord -D default -r 16000 -c 1 -f S16_LE -t wav -d 5 test1.wav
aplay -D default test1.wav
``` 

I've run the script and added the satellite to HA with: 

```shell
script/run \
  --debug \
  --name 'sat1' \
  --uri 'tcp://0.0.0.0:10700' \
  --mic-command 'arecord -D default -r 16000 -c 1 -f S16_LE -t raw' \
  --snd-command 'aplay -D default -r 22050 -c 1 -f S16_LE -t raw'
``` 

However, when I try to add the follwoing code to my systemd service unit file I continuously get an error:

```shell
Jan 14 00:26:25 pi4 run[5209]: ALSA lib pcm_asym.c:105:(_snd_pcm_asym_open) capture slave is not defined
Jan 14 00:26:25 pi4 run[5209]: arecord: main:831: audio open error: Invalid argument
Jan 14 00:26:25 pi4 run[5200]: WARNING:root:Mic service disconnected 
```

my systemd service file:

```shell
Description=Wyoming Satellite
Wants=network-online.target
After=network-online.target
Requires=wyoming-openwakeword.service

[Service]
Type=simple
ExecStart=/home/pi/wyoming-satellite/script/run --name 'kitchensat' \
    --uri 'tcp://0.0.0.0:10700' \
    --mic-command 'arecord -D default -r 16000 -c 1 -f S16_LE -t raw' \
    --snd-command 'aplay -D default -r 22050 -c 1 -f S16_LE -t raw' \
    --mic-auto-gain 5 \
    --mic-noise-suppression 2 \
    --wake-uri 'tcp://127.0.0.1:10400' \
    --wake-word-name 'hey_jarvis'
WorkingDirectory=/home/pi/wyoming-satellite
Restart=always
RestartSec=1

[Install]
WantedBy=default.target
```

At this point I'm a little lost. I can still record and play files while working in the virtual environment but the systemd service can't find the mic.

**Comment by llluis** [comment]
Just to be sure. If you run the script from command line it works but it does not from system service?

**Comment by TDX44** [comment]
That is correct. It runs perfectly from the command line.

**Comment by brewston** [comment]
If your systemd service file is a true copy/paste I see a wrapping problem :  

`-c >WorkingDirectory=/home/pi/wyoming-satellite`

WorkingDirectory should be on the next line and -c needs an arg

**Comment by llluis** [comment]
Maybe you have a `.asoundrc` in your home dir (defining your default output) and not a `/etc/asound.conf` system wide... 
You can try to replace the `default` by something more specific (see via `aplay -l`) or trying to copy/compare the `.asoundrc` and `asound.conf` if this is the case.

I had different messages regarding the "slave definition" and they were all related to the alsa config via those files.

**Comment by TDX44** [comment]
> Maybe you have a `.asoundrc` in your home dir (defining your default output) and not a `/etc/asound.conf` system wide... You can try to replace the `default` by something more specific (see via `aplay -l`) or trying to copy/compare the `.asoundrc` and `asound.conf` if this is the case.
> 
> I had different messages regarding the "slave definition" and they were all related to the alsa config via those files.

It seems I'm a little in over my head on this one but I read on the also website that neither the .asoundrc or the asound.conf are requried for operation but it genuinely sounds like this could be the issue. 


I've updated the looks of my systemd file due to a typo and now im getting the following after running the status command:

```shell
sudo systemctl status wyoming-satellite.service
● wyoming-satellite.service - Wyoming Satellite
     Loaded: loaded (/etc/systemd/system/wyoming-satellite.service; enabled; preset: enabled)
     Active: active (running) since Mon 2024-01-15 09:50:40 CST; 6s ago
   Main PID: 2295 (python3)
      Tasks: 2 (limit: 3912)
        CPU: 594ms
     CGroup: /system.slice/wyoming-satellite.service
             ├─2295 python3 /home/pi/wyoming-satellite/script/run --name kitchensat --uri tcp://0.0.0.0:10>
             └─2333 /home/pi/wyoming-satellite/.venv/bin/python3 -m wyoming_satellite --name kitchensat -->

Jan 15 09:50:40 pi4 systemd[1]: Started wyoming-satellite.service - Wyoming Satellite.
Jan 15 09:50:41 pi4 run[2333]: INFO:root:Ready
Jan 15 09:50:41 pi4 run[2333]: INFO:root:Connected to services
Jan 15 09:50:41 pi4 run[2342]: arecord: main:831: audio open error: No such file or directory
Jan 15 09:50:41 pi4 run[2333]: WARNING:root:Mic service disconnected
Jan 15 09:50:43 pi4 run[2333]: INFO:root:Waiting for wake word
Jan 15 09:50:44 pi4 run[2354]: arecord: main:831: audio open error: No such file or directory
Jan 15 09:50:44 pi4 run[2333]: WARNING:root:Mic service disconnected
lines 1-18/18 (END)
```

**Comment by llluis** [comment]
Are you still running with `-D default` ? What's the output of your `aplay -l`?

**Comment by llluis** [comment]
Maybe forgot the results of aplay? :)

**Comment by gravyflex** [comment]
I ran into this issue and the fix was adding the user and group to the systemd service file. 
```
User=<user>
Group=<group>
```

My current config example 
```sudo systemctl cat wyoming-satellite.service
# /etc/systemd/system/wyoming-satellite.service
[Unit]
Description=Wyoming Satellite
Wants=network-online.target
After=network-online.target
Requires=wyoming-openwakeword.service
# Requires=2mic_leds.service
Requires=pulseaudio.service

[Service]
Type=simple
User=<user>
Group=<group>
ExecStart=/home/<user>/wyoming-satellite/script/run \
    --name 'Office' \
    --uri 'tcp://0.0.0.0:10700' \
    --mic-command 'parecord --property=media.role=phone --rate=16000 --channels=1 --format=s16le --raw' \
    --snd-command 'paplay --property=media.role=announce --rate=44100 --channels=1 --format=s16le --raw' \
    --snd-command-rate 44100 \
    --snd-volume-multiplier 0.1 \
    --mic-auto-gain 7 \
    --mic-noise-suppression 3 \
    --wake-uri 'tcp://127.0.0.1:10400' \
    --wake-word-name 'hey_jarvis' \
    --detection-command '/home/<user>/wyoming-enhancements/snapcast/scripts/awake.sh' \
    --tts-stop-command '/home/<user>/wyoming-enhancements/snapcast/scripts/done.sh' \
    --awake-wav sounds/awake.wav \
    --done-wav sounds/done.wav \
    --debug
WorkingDirectory=/home/<user>/wyoming-satellite
Restart=always
RestartSec=1

[Install]
WantedBy=default.target```

**Comment by Gerw88** [comment]
I'm also stuck on this.
I'm on a Pi Zero W, Raspberry Pi OS 32-bit legacy, fresh install.
I'm using a RaspiAudio Mic+ v2 hat with PulseAudio as configured [here](https://forum.raspiaudio.com/t/mic-installation-guide/17)

```
Apr 08 19:43:42 pizero run[813]: ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused
Apr 08 19:43:42 pizero run[813]: arecord: main:830: audio open error: Connection refused
Apr 08 19:43:42 pizero run[811]: WARNING:root:Mic service disconnected
```

I used both `-D default` and `-D pulse`, and both worked with `arecord` and `aplay`. When run manually, works as expected. I can configure in HA, and can check the whole pipeline. But the above failure when trying to run as a service.

I added the user and group settings.
I checked out `.asoundrc` and copied it over to `/etc/asound.conf` (which didn't exist)
Then I tried @TDX44's config, and I get new errors.

Service Status with 'pulseaudio.service' commented out:
```
Apr 08 20:58:49 pizero systemd[1]: wyoming-satellite.service: Scheduled restart job, restart counter is at 5.
Apr 08 20:58:49 pizero systemd[1]: Stopped Wyoming Satellite.
Apr 08 20:58:49 pizero systemd[1]: wyoming-satellite.service: Start request repeated too quickly.
Apr 08 20:58:49 pizero systemd[1]: wyoming-satellite.service: Failed with result 'exit-code'.
Apr 08 20:58:49 pizero systemd[1]: Failed to start Wyoming Satellite.
```
Which unfortunately doesn't tell me much. From Journalctl log:

```
-- Journal begins at Tue 2024-03-12 01:14:29 GMT. --

```

**Comment by TDX44** [comment]
Not sure what's going on but I resolved this by switching away from Bluetooth and using only usb speakers/mics. 

Good luck.

**Comment by Gerw88** [comment]
Thanks @TDX44. Unfortunately I'm connected directly already(RaspiAudio Mic+ v2 hat). I think it's a bit beyond me to figure this out. I'll get a Pi ZW2 and try again.

I had a taste of it working from the command line and it was very cool, very responsive. :)

**Comment by rojoricardo** [comment]
@gravyflex excuse my ignorance, but what did you put in <Group> I understand <user> replace with "pi" or your "user" in case you changed it but what is the group?

**Comment by rwkeane** [comment]
Has anyone found a solution for this?  I am hitting the issue as of tonight, exactly as described above

For added info, I have found that:
- When started the code from systemd as either my user or root, I get the same behavior
- When run manually as my user it works
- When I run it manually as root it **fails with the same error**

So the issue is reproducable without going through systemd. For any users here with it working, what happens if you run the `script/run` as root?

**Comment by TDX44** [comment]
> Also, can we re-open this issue? Or should I re-file it?

You'd probably have better luck reopening as the original issue has been resolved.

**Comment by rwkeane** [comment]
I figured it out! For anyone else who hits this issue, you need to make your `arecord` command more explicit

Update it to `--mic-command '/usr/bin/arecord -D plughw:<id> [rest of command from docs]`

Where `<id>` comes from a call to `arecord -l`.
