### ISSUE TITLE
Unable to add satellite to Home Assistant

### ISSUE THREAD

**Issue by vehjelmtvedt** [rhasspy/wyoming-satellite#6]
Hello! I am running Home Assistant in a docker container, and would like this satellite get up and running so that I can use whisper and piper. I am also running the satellite, wake word service and wyoming external mic in docker as well. However, adding satellite to home assistant is not working.

**This is my docker compose.**
<img width="690" alt="Screenshot 2023-12-13 at 15 08 56" src="https://github.com/rhasspy/wyoming-satellite/assets/45099966/f99dcfb3-d32f-4050-b015-5b2495957f56">

First, the wyoming protocol is not being discovered in home assistant. Second, when I try to add it manually via its IP and port, home assistant says no service was found at endpoint.

<img width="422" alt="Screenshot 2023-12-13 at 15 46 43" src="https://github.com/rhasspy/wyoming-satellite/assets/45099966/33dd0489-9f45-4e70-8fac-aaf2df0dc5e2">

However, the satellite logs indicate a client was connected as can be seen in the picture below.

<img width="819" alt="Screenshot 2023-12-13 at 15 47 37" src="https://github.com/rhasspy/wyoming-satellite/assets/45099966/7cd77cdd-2035-4595-828d-684437ff4c2d">

It could be the case that this is an issue with home assistant and not wyoming-satellite, so feel free to close this if thats the case. Thank you :)

**Comment by joie96** [comment]
Did you update to newest homeassistent core? Make sure you are on version 2023.12.

**Comment by vehjelmtvedt** [comment]
Yeah that did the trick..Thank you @joie96!
