### ISSUE TITLE
typo? "wyoming-wakeword.service"  is "open" missing?

### ISSUE THREAD

**Issue by gitcrap** [rhasspy/wyoming-satellite#61]
https://github.com/rhasspy/wyoming-satellite/blob/3a91fc468a0d97bad12ecc79f4e4ca2e89cf8839/installer/services.py#L91

your old "tutorial_2mic.md" had us create this file:
sudo systemctl edit --force --full wyoming-openwakeword.service
...
and then Check logs with:
sudo systemctl status wyoming-satellite.service wyoming-openwakeword.service

has this changed?

**Comment by synesthesiam** [comment]
Since there's only one wakeword system expected to run at a time, I decided to make it a single service name for the installer.
