### ISSUE TITLE
LED Service not working on 2Mic HAT

### ISSUE THREAD

**Issue by atoulmin** [rhasspy/wyoming-satellite#62]
HI,

I've got everything working fine on my pizero2w and 2Mic Hat except for the LED service.  When i check to see if the service is installed properly it throws up this error.

`pi@raspberrypi:~/wyoming-satellite/examples $ .venv/bin/python3 2mic_service.py --help
Traceback (most recent call last):
  File "/home/pi/wyoming-satellite/examples/2mic_service.py", line 15, in <module>
    from wyoming.satellite import (
ImportError: cannot import name 'SatelliteConnected' from 'wyoming.satellite' (/home/pi/wyoming-satellite/examples/.venv/lib/python3.11/site-packages/wyoming/satellite.py)
pi@raspberrypi:~/wyoming-satellite/examples $`

I've tried 2-3 times from scratch and get the same error.  Any ideas?

**Comment by bbostock** [comment]
I have the exact same problem. Would really appreciate some help with debugging this.

**Comment by coxtor** [comment]
I fixed it - for some reason the pip package wyoming does not contain the dataclasses.

Quickfix:
you need to add the content of https://raw.githubusercontent.com/rhasspy/wyoming/a2f425951623e701b65d186f31faa24e2dfa167b/wyoming/satellite.py 

into 

wyoming-satellite/examples/.venv/lib/python3.9/site-packages/wyoming/satellite.py

**Comment by coxtor** [comment]
Ok it just moved the issue. It appears there is something wrong with the whole wyoming package

**Comment by j3tpropelled** [comment]
Assuming you're following and copy/pasting the tutorial on here, the tutorial section on setting up the LED needs updating.

The current document references wyoming 1.4.1 whereas it should be 1.5.2 (at present).

So run

cd wyoming-satellite/examples
python3 -m venv --system-site-packages .venv
.venv/bin/pip3 install --upgrade pip
.venv/bin/pip3 install --upgrade wheel setuptools
.venv/bin/pip3 install 'wyoming==1.5.2'
