### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/app/wyoming_satellite/VERSION'

### ISSUE THREAD

**Issue by andreasbrett** [rhasspy/wyoming-satellite#74]
PR for fixing issue https://github.com/rhasspy/wyoming-satellite/pull/73

After changes in https://github.com/rhasspy/wyoming-satellite/commit/5088b590a63da61c01db78d35c259a4babaf6e53, the Docker container crashes on startup when trying to read the file `VERSION`.

https://github.com/rhasspy/wyoming-satellite/blob/5088b590a63da61c01db78d35c259a4babaf6e53/wyoming_satellite/__init__.py#L20

This file is not allowlisted in `.dockerignore` and thus missing in the Docker image. Here's the error output.

```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/app/wyoming_satellite/__init__.py", line 20, in <module>
    __version__ = (_DIR / "VERSION").read_text(encoding="utf-8").strip()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/pathlib.py", line 1058, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/app/wyoming_satellite/VERSION'
Traceback (most recent call last):
  File "/app/script/run", line 12, in <module>
    subprocess.check_call([context.env_exe, "-m", "wyoming_satellite"] + sys.argv[1:])
  File "/usr/local/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/app/.venv/bin/python3', '-m', 'wyoming_satellite', '--uri', 'tcp://0.0.0.0:10700', '--name', 'Conference Phone', '--area', 'Wohnzimmer', '--mic-command', 'arecord -D plughw:CARD=USB,DEV=0 -r 16000 -c 1 -f S16_LE -t raw', '--snd-command', 'aplay -D plughw:CARD=USB,DEV=0 -r 22050 -c 1 -f S16_LE -t raw']' returned non-zero exit status 1.
```

**Comment by preimmortal** [comment]
I think the `.dockerignore` should be removed since any new file dependencies will break the container unless it is excluded from `.dockerignore` and added to the `Dockerfile`. Just my opinion since i've experienced several breakages due to file dependencies in the week i've been playing with this repo.

**Comment by synesthesiam** [comment]
Update the .dockerignore via a community member's PR.

It's important to keep this file to avoid unnecessary copies of .venv and the local directory being copied by the Docker build process.

**Comment by andreasbrett** [comment]
closed because https://github.com/rhasspy/wyoming-satellite/pull/73 got merged
