### ISSUE TITLE
Native tts and stt sensors in home assistant

### ISSUE THREAD

**Issue by blairun** [rhasspy/wyoming-satellite#8]
I'm using the --transcript-command and --synthesize-command options to trigger scripts which update sst and tts sensors in home assistant.  They're working well but it would be nicer to have all these [commands](https://github.com/rhasspy/wyoming-satellite#event-commands) exposed as sensors through the [native wyoming integration](https://github.com/home-assistant/core/tree/dev/homeassistant/components/wyoming).  Thanks for sharing this neat project.

**Comment by sayam93** [comment]
> I'm using the --transcript-command and --synthesize-command options to trigger scripts which update sst and tts sensors in home assistant. They're working well but it would be nicer to have all these [commands](https://github.com/rhasspy/wyoming-satellite#event-commands) exposed as sensors through the [native wyoming integration](https://github.com/home-assistant/core/tree/dev/homeassistant/components/wyoming). Thanks for sharing this neat project.

Could you share these scripts?

**Comment by blairun** [comment]
Sure. Here's a `--synthesize-command` script 


```bash
#!/usr/bin/env sh

text="$(cat)"
echo "Text to speech text: ${text}"

# Use attribute since replies can be more than 255 characters
HA_URL="https://home.example.com" # Replace with your Home Assistant URL
SENSOR_ENTITY_ID="sensor.assist_tts" # Replace with your sensor entity ID
ATTRIBUTE_NAME="tts" # Replace with the name of the attribute you want to update
NEW_ATTRIBUTE_VALUE=${text} # Replace with the new value for the attribute
ACCESS_TOKEN="abc123" # Replace with your actual home assistant token

# Update the sensor attribute
curl -X POST -H "Authorization: Bearer $ACCESS_TOKEN" \
     -H "Content-Type: application/json" \
     -d "{\"state\": \"state\", \"attributes\": {\"$ATTRIBUTE_NAME\": \"$NEW_ATTRIBUTE_VALUE\"}}" \
     "$HA_URL/api/states/$SENSOR_ENTITY_ID"

# echo "Sensor attribute updated."
```

And here's a `--transcript-command` script

```bash
#!/usr/bin/env sh

text="$(cat)"
echo "Speech to text transcript: ${text}"

# Use attribute since replies can be more than 255 characters
HA_URL="https://home.example.com" # Replace with your Home Assistant URL
SENSOR_ENTITY_ID="sensor.assist_stt" # Replace with your sensor entity ID
ATTRIBUTE_NAME="stt" # Replace with the name of the attribute you want to update
NEW_ATTRIBUTE_VALUE=${text} # Replace with the new value for the attribute
ACCESS_TOKEN="abc123" # Replace with your actual home assistant token

# Update the sensor attribute
curl -X POST -H "Authorization: Bearer $ACCESS_TOKEN" \
     -H "Content-Type: application/json" \
     -d "{\"state\": \"state\", \"attributes\": {\"$ATTRIBUTE_NAME\": \"$NEW_ATTRIBUTE_VALUE\"}}" \
     "$HA_URL/api/states/$SENSOR_ENTITY_ID"

# echo "Sensor attribute updated."
```

**Comment by sayam93** [comment]
> Sure. Here's a `--synthesize-command` script
> 
> ```shell
> #!/usr/bin/env sh
> 
> text="$(cat)"
> echo "Text to speech text: ${text}"
> 
> # Use attribute since replies can be more than 255 characters
> HA_URL="https://home.example.com" # Replace with your Home Assistant URL
> SENSOR_ENTITY_ID="sensor.assist_tts" # Replace with your sensor entity ID
> ATTRIBUTE_NAME="tts" # Replace with the name of the attribute you want to update
> NEW_ATTRIBUTE_VALUE=${text} # Replace with the new value for the attribute
> ACCESS_TOKEN="abc123" # Replace with your actual home assistant token
> 
> # Update the sensor attribute
> curl -X POST -H "Authorization: Bearer $ACCESS_TOKEN" \
>      -H "Content-Type: application/json" \
>      -d "{\"state\": \"state\", \"attributes\": {\"$ATTRIBUTE_NAME\": \"$NEW_ATTRIBUTE_VALUE\"}}" \
>      "$HA_URL/api/states/$SENSOR_ENTITY_ID"
> 
> # echo "Sensor attribute updated."
> ```
> 
> And here's a `--transcript-command` script
> 
> ```shell
> #!/usr/bin/env sh
> 
> text="$(cat)"
> echo "Speech to text transcript: ${text}"
> 
> # Use attribute since replies can be more than 255 characters
> HA_URL="https://home.example.com" # Replace with your Home Assistant URL
> SENSOR_ENTITY_ID="sensor.assist_stt" # Replace with your sensor entity ID
> ATTRIBUTE_NAME="stt" # Replace with the name of the attribute you want to update
> NEW_ATTRIBUTE_VALUE=${text} # Replace with the new value for the attribute
> ACCESS_TOKEN="abc123" # Replace with your actual home assistant token
> 
> # Update the sensor attribute
> curl -X POST -H "Authorization: Bearer $ACCESS_TOKEN" \
>      -H "Content-Type: application/json" \
>      -d "{\"state\": \"state\", \"attributes\": {\"$ATTRIBUTE_NAME\": \"$NEW_ATTRIBUTE_VALUE\"}}" \
>      "$HA_URL/api/states/$SENSOR_ENTITY_ID"
> 
> # echo "Sensor attribute updated."
> ```

Thanks for this!
