### ISSUE TITLE
Wake word does not work if defined in the CLI

### ISSUE THREAD

**Issue by RobertLukan** [rhasspy/wyoming-satellite#93]
If I define a wake word in CLI it does not detect it. I am on the latest version(with additional button functionality), I noticed the same behaviour even with one of the versions before.

I run the latest openwakeword on another server as this RPI is busy enough.

Not working example:
pi@rpi-cm4-3:~/wyoming-satellite-modified/wyoming-satellite $ script/run   --debug   --name 'my satellite'   --uri 'tcp://0.0.0.0:10700'   --mic-command 'arecord -q -r 16000 -f S16_LE -c 1 -t raw -D plughw:CARD=ArrayUAC10,DEV=0'  --snd-command 'aplay -D plughw:CARD=MAX98357A,DEV=0 -r 22050 -c 1 -f S16_LE -t raw' --snd-volume-multiplier 0.25  --wake-uri 'tcp://192.168.123.10:10400'   --debug --awake-wav sounds/awake.wav --done-wav sounds/done.wav --vad **--wake-word='alexa'**
VAD is not used with local wake word detection
DEBUG:root:Namespace(mic_uri=None, mic_command='arecord -q -r 16000 -f S16_LE -c 1 -t raw -D plughw:CARD=ArrayUAC10,DEV=0', mic_command_rate=16000, mic_command_width=2, mic_command_channels=1, mic_command_samples_per_chunk=1024, mic_volume_multiplier=1.0, mic_noise_suppression=0, mic_auto_gain=0, snd_uri=None, snd_command='aplay -D plughw:CARD=MAX98357A,DEV=0 -r 22050 -c 1 -f S16_LE -t raw', snd_command_rate=22050, snd_command_width=2, snd_command_channels=1, snd_volume_multiplier=0.25, wake_uri='tcp://192.168.123.10:10400', wake_word_name=['alexa'], wake_command=None, wake_command_rate=16000, wake_command_width=2, wake_command_channels=1, wake_refractory_seconds=5.0, vad=True, vad_threshold=0.5, vad_trigger_level=1, vad_buffer_seconds=2, vad_wake_word_timeout=5.0, event_uri=None, startup_command=None, detect_command=None, detection_command=None, transcript_command=None, stt_start_command=None, stt_stop_command=None, synthesize_command=None, tts_start_command=None, tts_stop_command=None, streaming_start_command=None, streaming_stop_command=None, error_command=None, connected_command=None, disconnected_command=None, awake_wav='sounds/awake.wav', done_wav='sounds/done.wav', uri='tcp://0.0.0.0:10700', name='my satellite', area=None, no_zeroconf=False, zeroconf_name=None, zeroconf_host=None, debug_recording_dir=None, debug=True, log_format='%(levelname)s:%(name)s:%(message)s')
WARNING:root:VAD is enabled but will not be used
INFO:root:Ready
DEBUG:root:Detected IP: 192.168.1.160
DEBUG:root:Zeroconf discovery enabled (name=d83addaade95, host=None)
DEBUG:root:Connecting to mic service: ['arecord', '-q', '-r', '16000', '-f', 'S16_LE', '-c', '1', '-t', 'raw', '-D', 'plughw:CARD=ArrayUAC10,DEV=0']
DEBUG:root:Connecting to snd service: ['aplay', '-D', 'plughw:CARD=MAX98357A,DEV=0', '-r', '22050', '-c', '1', '-f', 'S16_LE', '-t', 'raw']
DEBUG:root:Connecting to wake service: tcp://192.168.123.10:10400
INFO:root:Connected to services
DEBUG:root:Connected to mic service
DEBUG:root:Connected to wake service
DEBUG:root:Server set: 50669091923315
INFO:root:Connected to server
INFO:root:Waiting for wake word

Working example:
pi@rpi-cm4-3:~/wyoming-satellite-modified/wyoming-satellite $ script/run   --debug   --name 'my satellite'   --uri 'tcp://0.0.0.0:10700'   --mic-command 'arecord -q -r 16000 -f S16_LE -c 1 -t raw -D plughw:CARD=ArrayUAC10,DEV=0'  --snd-command 'aplay -D plughw:CARD=MAX98357A,DEV=0 -r 22050 -c 1 -f S16_LE -t raw' --snd-volume-multiplier 0.25  --wake-uri 'tcp://192.168.123.10:10400'   --debug --awake-wav sounds/awake.wav --done-wav sounds/done.wav --vad
VAD is not used with local wake word detection
DEBUG:root:Namespace(mic_uri=None, mic_command='arecord -q -r 16000 -f S16_LE -c 1 -t raw -D plughw:CARD=ArrayUAC10,DEV=0', mic_command_rate=16000, mic_command_width=2, mic_command_channels=1, mic_command_samples_per_chunk=1024, mic_volume_multiplier=1.0, mic_noise_suppression=0, mic_auto_gain=0, snd_uri=None, snd_command='aplay -D plughw:CARD=MAX98357A,DEV=0 -r 22050 -c 1 -f S16_LE -t raw', snd_command_rate=22050, snd_command_width=2, snd_command_channels=1, snd_volume_multiplier=0.25, wake_uri='tcp://192.168.123.10:10400', wake_word_name=[], wake_command=None, wake_command_rate=16000, wake_command_width=2, wake_command_channels=1, wake_refractory_seconds=5.0, vad=True, vad_threshold=0.5, vad_trigger_level=1, vad_buffer_seconds=2, vad_wake_word_timeout=5.0, event_uri=None, startup_command=None, detect_command=None, detection_command=None, transcript_command=None, stt_start_command=None, stt_stop_command=None, synthesize_command=None, tts_start_command=None, tts_stop_command=None, streaming_start_command=None, streaming_stop_command=None, error_command=None, connected_command=None, disconnected_command=None, awake_wav='sounds/awake.wav', done_wav='sounds/done.wav', uri='tcp://0.0.0.0:10700', name='my satellite', area=None, no_zeroconf=False, zeroconf_name=None, zeroconf_host=None, debug_recording_dir=None, debug=True, log_format='%(levelname)s:%(name)s:%(message)s')
WARNING:root:VAD is enabled but will not be used
INFO:root:Ready
DEBUG:root:Detected IP: 192.168.1.160
DEBUG:root:Zeroconf discovery enabled (name=d83addaade95, host=None)
DEBUG:root:Connecting to mic service: ['arecord', '-q', '-r', '16000', '-f', 'S16_LE', '-c', '1', '-t', 'raw', '-D', 'plughw:CARD=ArrayUAC10,DEV=0']
DEBUG:root:Connecting to snd service: ['aplay', '-D', 'plughw:CARD=MAX98357A,DEV=0', '-r', '22050', '-c', '1', '-f', 'S16_LE', '-t', 'raw']
DEBUG:root:Connecting to wake service: tcp://192.168.123.10:10400
INFO:root:Connected to services
DEBUG:root:Connected to mic service
DEBUG:root:Connected to wake service
DEBUG:root:Server set: 51097474228435
INFO:root:Connected to server
INFO:root:Waiting for wake word
DEBUG:root:Streaming audio
DEBUG:root:Muting microphone for 0.8995918367346939 second(s)
WARNING:root:Event(type='error', data={'text': 'speech-to-text failed', 'code': 'stt-stream-failed'}, payload=None)
INFO:root:Waiting for wake word
DEBUG:root:Connected to snd service
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
DEBUG:root:Unmuted microphone
^CDEBUG:root:Stopping microphone service

**Comment by llluis** [comment]
Parameter is `--wake-word-name` and not `--wake-word`. Also it must be pre-loaded in the openwakeword service.

**Comment by RobertLukan** [comment]
Still the same. It could be something hardware related but it works with Rhasspy2 and Rhasspy3. I will go towards Rhasspy3 for now.
